FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN apk add --no-cache openssl

COPY . .

# Générer Prisma client
RUN npx prisma generate

EXPOSE 5000

CMD ["npm", "run", "dev"]
